nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        tags:
            - name: "Categories"
              description: "Accès aux categories"
            - name: "Evenements"
              description: "Accès aux événements"
            - name: "User"
              description: "Accès aux utilisateurs"
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
